### ISSUE TITLE
Search splitting terms by letter instead of word

### ISSUE THREAD

**Issue by git2samus** [GoogleChromeLabs/pptr.dev#10]
It seems there's a problem with the way the search terms are parsed, screenshot attached.

![50309846_10161616117020085_5119077696541818880_o](https://user-images.githubusercontent.com/146392/53842913-9a156280-3f7f-11e9-9540-bc651bacacf7.jpg)

**Comment by aslushnikov** [comment]
@git2samus so what's the problem?

**Comment by git2samus** [comment]
@aslushnikov I'm searching for the term "scroll" and I'm not getting results for that word but each separate letter instead.

**Comment by aslushnikov** [comment]
@git2samus yeah, there's no API method or event that has a word "scroll" in there. What are you looking for exactly?

**Comment by JoelEinbinder** [comment]
Working as intended.
See: https://en.wikipedia.org/wiki/Approximate_string_matching

**Comment by git2samus** [comment]
It's not what I'm looking exactly it's the fact that it's not searching for the terms but instead for the individual letters and that doesn't make sense.

If there's no matches then it should tell me that, the current search result isn't really useful.

**Comment by aslushnikov** [comment]
> If there's no matches then it should tell me that, the current search result isn't really useful.

@git2samus ah yeah, that'd be a substring search. As Joel mentioned, we do a fuzzy search instead, so you can search for `evaldoc` and get a `page.evaluateOnNewDocument` as a result. It also works nicely when there's an unfortunate typo in your search request or when you want to explore the API.
