### ISSUE TITLE
pptr.dev shows blank page in a case if service worker is not available

### ISSUE THREAD

**Issue by FlyingDR** [GoogleChromeLabs/pptr.dev#3]
pptr.dev uses service worker as its core, but it is possible that service workers are not available. It can be so in older browers, but service workers are also disabled in Firefox when page is open in private browser mode (see [reference in documentation](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) and [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1320796)). It makes site to display blank page without giving any information for the visitor about reason of the problem. 

It would be good to display something on the page in a case if service worker is not available in browser so users will not stuck.

**Comment by aslushnikov** [comment]
Interesting! I wonder why absense of service worker support results in an empty page: the website should load just fine from network. 

Thanks for reporting this.

**Comment by saberworks** [comment]
ETA on a fix for this?  I browse in private mode almost exclusively and this issue is problematic.

**Comment by aslushnikov** [comment]
It turns out this happens because Firefox Private Browsing prohibits use of IndexedDB. 

https://pptr.dev uses IndexedDB to cache documentations and release information for puppeteer versions. Caching is important so that we don't hit github/npm too much.

To fix Firefox Private Browsing, we will need to add a fallback to localstorage.

**Comment by aslushnikov** [comment]
For the record: this is a long-standing firefox bug - https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by aslushnikov** [comment]
Fixed and deployed a new website version - please check it out.

**Comment by saberworks** [comment]
It works now, thank you!!
